language: cpp
sudo: required
dist: trusty
compiler:
  - gcc
os:
  - linux
addons:
  apt:
    sources:
    # add PPAs with more up-to-date toolchains
    - ubuntu-toolchain-r-test
    - libgtest-dev
    packages:
    # install toolchains
    - g++-7
    - libgtest-dev
env:
  - BUILD_TYPE=Debug
  - BUILD_TYPE=Release
script:
  - sudo unlink /usr/bin/gcc
  - sudo ln -s /usr/bin/gcc-7 /usr/bin/gcc
  - sudo unlink /usr/bin/g++
  - sudo ln -s /usr/bin/g++-7 /usr/bin/g++
  - g++ -v
  - grep CXX_COMPILER CMakeLists.txt
  - ./build.sh install